#### NumPy Arrays

In [1]:
import numpy as np

In [4]:
mylist = [1, 2, 3]
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np.array(my_matrix)         # a two dimensional data, list inside a list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)        # creates an array starts from 0 to 10(not included)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 101, 4)    # np.arange(start, end, stepsize)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [13]:
np.zeros(5)             # creates a vector containing zeros, given parameter is the number of zeros

array([0., 0., 0., 0., 0.])

In [16]:
# To create a two dimensional array
np.zeros((2,7))         # a two dimensional array with 2 rows and 7 columns

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((3, 4))         # a list of 1s with 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.linspace(0, 10, 11)  # returns evenly spaces numbers over a specified interval
# for example
print(np.linspace(1, 9, 5))    # it includes the end
print(len(np.linspace(1, 9, 5)))    # len() gives back the same number we gave

[1. 3. 5. 7. 9.]
5


In [40]:
np.eye(5)       # np.eye(n) gives back an nxn identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.random.rand(1)       # gives back a number between 0 and 1, with mutual likely hood

array([0.73765591])

In [45]:
np.random.rand(5, 2)

array([[0.19336573, 0.61582896],
       [0.36407754, 0.93661543],
       [0.89941874, 0.13445698],
       [0.61169091, 0.83620562],
       [0.01890428, 0.05399443]])

In [46]:
np.random.randn(10)

array([-0.16452115, -0.87872973, -0.15907528, -0.53322256, -0.70765135,
        1.12848094,  0.73170216,  0.62261657,  1.6291295 ,  1.45985588])

In [55]:
np.random.randn(4,2)    # np.random.randn(a, b) returns a axb matrix consist of the values taken from the standard normal distribution

array([[ 0.11700174,  0.09004982],
       [ 0.55853093, -0.25132088],
       [ 0.22542049,  0.22912938],
       [-1.15834203, -1.14041409]])

In [54]:
np.random.randint(0, 1999, (4, 5))       # np.random.randint(a, b, (n,m)) returns a nxm matrix consists of random numbers between a and b(excluded)

array([[1750, 1992,  220,  356, 1135],
       [1042,   56,  672,  182,  376],
       [ 814, 1430,  599, 1304,  724],
       [1912, 1490, 1247,  374,   27]])

In [57]:
np.random.randint(0, 80, (4, 5))        # for example this can be described to make a dataset of peoples age

array([[19, 14, 69,  9, 75],
       [16, 53, 73, 38, 74],
       [ 1,  1, 62, 70, 45],
       [71, 28, 65, 54, 60]])

In [61]:
np.random.seed(42)          # sets a particular set of random numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [62]:
arr = np.arange(0, 25)

In [63]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([ 14,  61,  61,  46,  61,  50,  54,  63,   2, 100])

In [71]:
ranarr.max()
ranarr.min()

2

In [73]:
ranarr.argmax()         # the maximum value is found at index location 9
ranarr.argmin()         # the minimum value is found at index location 8

8

In [74]:
ranarr.dtype

dtype('int64')

In [76]:
ranarr.shape            # you have 10 numbers in it 

(10,)

In [81]:
ranarr.reshape(2, 5)

array([[ 14,  61,  61,  46,  61],
       [ 50,  54,  63,   2, 100]])

In [82]:
ranarr.shape

(10,)

#### NumPy Indexing and Selection

In [85]:
import numpy as np

In [87]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[8]

8

In [92]:
arr[1 : 5]          # start from 1 ends at 4 excluding 5
arr[0 : 5]          # start from the begining end before 5

array([0, 1, 2, 3, 4])