#### NumPy Arrays

In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3]
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np.array(my_matrix)         # a two dimensional data, list inside a list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)        # creates an array starts from 0 to 10(not included)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 101, 4)    # np.arange(start, end, stepsize)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [9]:
np.zeros(5)             # creates a vector containing zeros, given parameter is the number of zeros

array([0., 0., 0., 0., 0.])

In [10]:
# To create a two dimensional array
np.zeros((2,7))         # a two dimensional array with 2 rows and 7 columns

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3, 4))         # a list of 1s with 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0, 10, 11)  # returns evenly spaces numbers over a specified interval
# for example
print(np.linspace(1, 9, 5))    # it includes the end
print(len(np.linspace(1, 9, 5)))    # len() gives back the same number we gave

[1. 3. 5. 7. 9.]
5


In [13]:
np.eye(5)       # np.eye(n) gives back an nxn identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(1)       # gives back a number between 0 and 1, with mutual likely hood

array([0.87671311])

In [15]:
np.random.rand(5, 2)

array([[0.78522962, 0.6069435 ],
       [0.8209375 , 0.01795502],
       [0.43943358, 0.94160608],
       [0.31483593, 0.87690512],
       [0.04034491, 0.07687894]])

In [16]:
np.random.randn(10)

array([ 0.23283655, -0.27430013,  0.39365676, -0.77765724,  1.40981414,
       -0.08850863, -1.3329322 , -1.80912219,  0.45998818,  0.99907778])

In [17]:
np.random.randn(4,2)    # np.random.randn(a, b) returns a axb matrix consist of the values taken from the standard normal distribution

array([[ 1.59999249, -0.27246951],
       [-0.83706149,  0.17175127],
       [ 0.58268453,  1.01939129],
       [ 0.74164949, -0.51317815]])

In [18]:
np.random.randint(0, 1999, (4, 5))       # np.random.randint(a, b, (n,m)) returns a nxm matrix consists of random numbers between a and b(excluded)

array([[1538,  774,  907, 1845, 1388],
       [1260, 1226,  317,   58,  759],
       [1303, 1893, 1573,  441, 1762],
       [1522, 1257,  770, 1983, 1496]])

In [19]:
np.random.randint(0, 80, (4, 5))        # for example this can be described to make a dataset of peoples age

array([[29, 35, 39, 54, 50],
       [77, 46, 50, 67,  8],
       [ 0, 20, 62, 38, 58],
       [10, 41, 24,  4, 53]])

In [20]:
np.random.seed(42)          # sets a particular set of random numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
arr = np.arange(0, 25)

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [24]:
ranarr.max()
ranarr.min()

2

In [25]:
ranarr.argmax()         # the maximum value is found at index location 9
ranarr.argmin()         # the minimum value is found at index location 8

7

In [26]:
ranarr.dtype

dtype('int64')

In [27]:
ranarr.shape            # you have 10 numbers in it 

(10,)

In [28]:
ranarr.reshape(2, 5)

array([[82, 86, 74, 74, 87],
       [99, 23,  2, 21, 52]])

In [29]:
ranarr.shape

(10,)

#### NumPy Indexing and Selection

In [30]:
import numpy as np

In [31]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[8]

8

In [33]:
arr[1 : 5]          # start from 1 ends at 4 excluding 5
arr[0 : 5]          # start from the begining end before 5

array([0, 1, 2, 3, 4])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[0:5] = 100      # slice up the array and change the values
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
arr = np.arange(0, 11)

In [37]:
slice_of_arr = arr[0:5]             # this acts as a pointer to the original array

In [38]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [39]:
slice_of_arr[:] = 99
arr               # to avoid the pointer issue, we need to set up a copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [40]:
arr_copy = arr.copy()

In [41]:
arr_copy[:] = 100
print(arr_copy)
arr

[100 100 100 100 100 100 100 100 100 100 100]


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d.shape            # returns # of rows and # of columns

(3, 3)

In [46]:
arr_2d[0]

array([ 5, 10, 15])

In [47]:
arr_2d[-1][2]          # returns the last row and gives the column number

45

In [49]:
arr_2d[:2, 1:]         # slice from start to the end(excluded), and start from the index column 1

array([[10, 15],
       [25, 30]])

In [50]:
arr = np.arange(1, 11)

In [51]:
arr > 4               # returns an array of bolian values

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
bool_arr = arr > 4

In [53]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]         # returns an array where only the boolians happens to be true
arr[arr > 4]          # same

array([ 5,  6,  7,  8,  9, 10])

In [59]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
arr_over_2 = dice_rolls > 2
len(dice_rolls[arr_over_2])

19

## NumPy Operations

In [60]:
import numpy as np

In [67]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [68]:
arr / arr

/tmp/ipykernel_16302/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
1 / arr

/tmp/ipykernel_16302/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr.sum()

45

In [73]:
arr.mean()

4.5

In [74]:
arr.var()

8.25

In [75]:
arr.std()

2.8722813232690143

In [84]:
arr2d = np.arange(0, 25).reshape(5, 5)
print(arr2d)
print(" " + "{}".format(arr2d.sum(axis=0)))         # returns the sum across the columns(sum of first,second, third...)
print(arr2d.sum(axis=1))         # returns the sum across the rows

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 [50 55 60 65 70]
[ 10  35  60  85 110]
